### PR TITLE
showing and printing diary entries upon diary nav link click

### PR DESCRIPTION
**Pull request by samueltrejo**

### CODE REVIEW

**Comment by sarahjulesthorne** [comment]
Hey, the content is not visible to me at all. I tried changing the a tag to a button tag with type set to button an dclass of btn, to cover all the bases,a nd I don't think that's the issue. My next best bet is that it's the media classes you're using on your domString.

**Review by bobbybaxter — CHANGES_REQUESTED** [review]
it works for me.  i had to `npm install` to make sure i had firebase installed, but i also needed to log in to get a `uid` then update those in the .json file.  

since we've all been logged in now, would it be too much trouble to add Sarah and my `uid` to all the seed data so we all have it for future reviews?  i promise, seed data hell will be over for you after that.

**Comment by samueltrejo** [comment]
should we merge, and I will do a seperate branch for seed data update?

**Comment by bobbybaxter** [comment]
sure, either way works.

**Comment by samueltrejo** [comment]
cool, merging code, everybody pull down

**Pull request merged**
