### PR TITLE
bb-navbar-setup

### PR DESCRIPTION
**Pull request by bobbybaxter**
you'll need to `npm install --save @fortawesome/fontawesome-free` for this to work correctly

### CODE REVIEW

**Comment by samueltrejo** [comment]
in `main.js` import navbar from `'./components/navbar/navbar';` not working, did you maybe change and didnt submit changes

**Comment by samueltrejo** [comment]
is it only supposed to show diary, and is dashboard button supposed to hide diary and show dashboard again?

**Comment by bobbybaxter** [comment]
since everyone's isn't added yet, i was thinking we'd add that individually.  but i can add that if you want.

**Comment by samueltrejo** [comment]
nah that's cool, just checking to make sure i didn't miss something, looks good

**Comment by samueltrejo** [comment]
👍

**Pull request merged**
